dqn:
  CartPole-v0:
    algo_name: dqn
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 64
    logger: tensorboard

  CartPole-v1:
    algo_name: dqn
    learning_rate: 0.01
    min_learning_rate: 1.0e-5
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    n_steps: 3

ddqn:
  CartPole-v0:
    algo_name: ddqn
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 64
    double_dqn: True

  CartPole-v1:
    algo_name: ddqn
    learning_rate: 0.01
    min_learning_rate: 1.0e-5
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    double_dqn: True
    n_steps: 3

dueling_dqn:
  CartPole-v0:
    algo_name: dueling_dqn
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 64
    dueling_dqn : True

  CartPole-v1:
    algo_name: dueling_dqn
    learning_rate: 0.01
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    dueling_dqn : True
    n_steps: 3

dueling_ddqn:
  CartPole-v0:
    algo_name: dueling_ddqn
    learning_rate: 0.01
    max_timesteps: 20000
    buffer_size: 10000
    batch_size: 64
    double_dqn: True
    dueling_dqn: True

  CartPole-v1:
    algo_name: dueling_ddqn
    learning_rate: 0.01
    max_timesteps: 100000
    buffer_size: 10000
    batch_size: 64
    double_dqn: True
    dueling_dqn: True
    n_steps: 3

c51:
  CartPole-v0:
    algo_name: c51
    learning_rate: 1.0e-4
    max_timesteps: 30000
    buffer_size: 10000
    target_update_frequency: 100
    train_frequency: 10
    gradient_steps: 5
    batch_size: 128

ddpg:
  Pendulum-v1:
    algo_name: ddpg
    actor_lr: 1.0e-2
    critic_lr: 1.0e-3
    max_timesteps: 200000
    buffer_size: 20000
    use_smooth_l1_loss: True
    target_update_frequency: 1
    soft_update_tau: 0.01
    train_frequency: 10
    gradient_steps: 5
    batch_size: 256
    logger: tensorboard

ppo_clip:
  CartPole-v0:
    algo_name: ppo_clip
    max_timesteps: 50000
    learning_rate: 1.0e-3
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb

  CartPole-v1:
    algo_name: ppo_clip
    max_timesteps: 300000
    learning_rate: 1.0e-3
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb


ppo_penalty:
  CartPole-v0:
    algo_name: ppo_penalty
    max_timesteps: 50000
    actor_lr: 1.0e-3
    critic_lr: 1.0e-2
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb

  CartPole-v1:
    algo_name: ppo_penalty
    max_timesteps: 300000
    actor_lr: 1.0e-3
    critic_lr: 1.0e-2
    buffer_size: 128
    rollout_steps: 128
    batch_size: 32
    logger: wandb
